<a href="https://colab.research.google.com/github/imshubhamgoyal/top_n_recommendation/blob/master/EvaluatingResults.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# from google.colab import files
# files.upload()
from google.colab import drive 
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:

import json
from scipy import spatial

import numpy as np 
import pandas as pd
from pandas.tools.plotting import scatter_matrix
from random import randint
from sklearn.cluster import KMeans
import numpy as np
from scipy import spatial
from operator import itemgetter
from scipy.cluster.vq import vq, kmeans, whiten
import matplotlib.pyplot as plt

Dataset='Jester Dataset'

In [0]:
global_text=open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/global.json').read()
global_df=np.array(json.loads(global_text))

In [0]:
input_text = open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/local.json').read()
local_df=np.array(json.loads(input_text))

In [8]:
print(global_df.shape)
print(local_df.shape)

(100, 100)
(10, 100, 100)


In [78]:
import random
users=random.sample(range(23499),2000)
print(users)

[21032, 6380, 16429, 3452, 11744, 21292, 8797, 1577, 13465, 19109, 20048, 15423, 9333, 3410, 13676, 6332, 8342, 16336, 11429, 20856, 5261, 15542, 14563, 6974, 18743, 445, 8126, 4043, 22877, 8854, 6530, 17634, 14784, 1803, 8463, 19743, 11773, 2776, 14902, 18070, 7237, 318, 17106, 17901, 12167, 10731, 6310, 17284, 6879, 15993, 6836, 10741, 13502, 11343, 7988, 3182, 18898, 359, 20777, 4361, 12910, 12584, 17276, 18254, 12782, 16044, 19647, 20880, 1197, 17258, 2620, 16189, 17838, 18782, 13355, 4027, 3125, 8254, 14382, 4969, 17819, 495, 6028, 11010, 7227, 6672, 13424, 15593, 4159, 17692, 21476, 22020, 2959, 7461, 15293, 13760, 3331, 4420, 7482, 19982, 14649, 14804, 22609, 6620, 3509, 11102, 2075, 8838, 16012, 2728, 1856, 12425, 7695, 14546, 7108, 16894, 18390, 21588, 18079, 16528, 2817, 14460, 21872, 11256, 12749, 12010, 3384, 2135, 15053, 14690, 15879, 19037, 16920, 16537, 5862, 16835, 18937, 17391, 4437, 13456, 4101, 19763, 13417, 10925, 23122, 13307, 7513, 6659, 22568, 12692, 7127, 17520,

In [0]:
# d1=dict()
# user=set()
# item=set()
# with open('/content/drive/My Drive/IIITD/CF_project/MovieLens Dataset/u.data') as f:
#     for line in f:
#         l1=line.split('\t')
#         u=int(l1[0])
#         i=int(l1[1])
#         rat=int(l1[2])
#         user.add(u)
#         item.add(i)
#         d1[(u,i)]=rat
# tt=int(len(user)/5)+1

# mat=np.zeros((len(user),len(item)))

# for ele in d1:
#     u=ele[0]-1
#     i=ele[1]-1
#     rat=d1[ele]
#     mat[u,i]=rat

# no_of_cluster=10
# kmeans = KMeans(n_clusters=10, random_state=0).fit(mat)
# d1=dict()
# clusters=[[]]*no_of_cluster
# for i in range(len(kmeans.labels_)):
#   label=kmeans.labels_[i]
#   clusters[label].append(i)
#   d1[i]=label
import pickle

dfile = open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/cluster_10', 'rb')
d1=pickle.load(dfile)                      
dfile.close() 

dfile = open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/rating_Matrix', 'rb')       
mat=pickle.load(dfile)
##### d1 gives cluster label of users

##### mat is rating matrix


In [0]:
no_of_users=mat.shape[0]
no_of_items=mat.shape[1]


In [12]:
print(mat.shape)

(23500, 100)


In [79]:
g=[None]*no_of_users

for u in users:
  clust_label=d1[u]
#   print(clust_label)
  numerator=0
  denominator=0
  for i in range(no_of_items):
    local_sim=0
    global_sim=0
    for l in range(no_of_items):
      if mat[u][l]!=0:
        local_sim+=local_df[clust_label][l][i]
        global_sim+=global_df[l][i]

    numerator+=(global_sim-local_sim)*(mat[u][i]-local_sim)
    denominator+=(global_sim-local_sim)*(global_sim-local_sim)
  g[u]=float(numerator/denominator)
  print(g[u])
print("ok")
# pickleObject=open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/calculated_gu','wb')
# pickle.dump(g,pickleObject)

-0.7594579790469856
-1.4834380904371351
7.3618900107719965
2.6172528718271737
-1.530879202736834
3.3099649293379447
4.133514275997221
7.312059406117261
2.8339295954082973
-0.06526216190182793
-0.21273956003187638
-0.5716932435815535
2.6816406452013357
4.086429722190385
0.8090320726704227
7.095710602870977
-0.8420038786327774
2.806301902398625
2.5613242271890857
-0.6136728546545638
-0.09784004728938861
-0.8235075083966072
-0.5881008425809511
-1.0640486073227522
-1.559786249007366
-0.8383665459366879
0.7799294983918429
-0.6126272436685218
-0.7989371297232162
-0.8696762602001827
-0.1254821572753097
4.0826510125481255
7.186159838419766
-0.5263611746813739
7.090054880475264
6.6608785694146535
7.123686637617155
-1.6699668042965654
7.246910279567264
4.139994887936931
2.70150709595879
-0.6207127583496956
-0.765325930863533
3.9832022371345706
7.121881486097319
3.173941165173689
-0.6205856790865532
-0.6297287224409261
-1.4996425131833424
-0.6067404753773274
-0.12015141843077619
-0.57933152350873

In [80]:
g=np.array(g)
print(g[users])
mini=g[users].min()
print(mini)
g[users]=g[users]-mini
maxi=g[users].max()
print(maxi)
g[users]=g[users]/maxi
print(g[users])

[-0.7594579790469856 -1.4834380904371351 7.3618900107719965 ...
 -0.97161987733199 4.050090626872547 3.9842385816484347]
-1.698171895372483
9.214642118139396
[0.10187198854718414 0.023303542577376452 0.9832245018294721 ...
 0.07884755682591794 0.6238183153016157 0.6166718581327063]


In [31]:
# u=0
# i=0
# print(local_df[8][:5,:5])
# print(global_df[:5,:5])
# labl=d1[u]
# local_local=0
# global_global=0
# for l in range(no_of_items):
#   if(mat[l][i]!=0):
#     local_local+=local_df[labl][l][i]
#     global_global+=global_df[l][i]
# print(local_local)
# print(global_global)

[[1.         0.83603864 0.85257945 0.81761196 0.67159818]
 [0.83603864 1.         0.81037074 0.78272175 0.69608988]
 [0.85257945 0.81037074 1.         0.82240783 0.67609719]
 [0.81761196 0.78272175 0.82240783 1.         0.64420958]
 [0.67159818 0.69608988 0.67609719 0.64420958 1.        ]]
[[1.         0.83603864 0.85257945 0.81761196 0.67159818]
 [0.83603864 1.         0.81037074 0.78272175 0.69608988]
 [0.85257945 0.81037074 1.         0.82240783 0.67609719]
 [0.81761196 0.78272175 0.82240783 1.         0.64420958]
 [0.67159818 0.69608988 0.67609719 0.64420958 1.        ]]


In [84]:

# g=[0.5]*(no_of_users)

pred_rating=np.zeros((no_of_users,no_of_items))

# for u in range(no_of_users):
for u in users:
  for i in range(no_of_items):
    summ=0
    sum1=0
    sum2=0
    clust_label=d1[u]
    for l in range(no_of_items):
      if(mat[u][l]!=0):
    #     summ+=g[u]*global_df[l][i]+(1-g[u])*local_df[clust_label][l][i]
        sum1+=global_df[l][i]
        sum2+=local_df[clust_label][l][i]

    pred_rating[u][i]=g[u]*sum1+(1-g[u])*sum2
#     print("final sum", pred_rating[u][i])
  print("user",u)

user 21032
user 6380
user 16429
user 3452
user 11744
user 21292
user 8797
user 1577
user 13465
user 19109
user 20048
user 15423
user 9333
user 3410
user 13676
user 6332
user 8342
user 16336
user 11429
user 20856
user 5261
user 15542
user 14563
user 6974
user 18743
user 445
user 8126
user 4043
user 22877
user 8854
user 6530
user 17634
user 14784
user 1803
user 8463
user 19743
user 11773
user 2776
user 14902
user 18070
user 7237
user 318
user 17106
user 17901
user 12167
user 10731
user 6310
user 17284
user 6879
user 15993
user 6836
user 10741
user 13502
user 11343
user 7988
user 3182
user 18898
user 359
user 20777
user 4361
user 12910
user 12584
user 17276
user 18254
user 12782
user 16044
user 19647
user 20880
user 1197
user 17258
user 2620
user 16189
user 17838
user 18782
user 13355
user 4027
user 3125
user 8254
user 14382
user 4969
user 17819
user 495
user 6028
user 11010
user 7227
user 6672
user 13424
user 15593
user 4159
user 17692
user 21476
user 22020
user 2959
user 7461
user 15293

In [0]:
# d1=dict()
# user=set()
# item=set()
# with open('/content/drive/My Drive/IIITD/CF_project/MovieLens Dataset/u.data') as f:
#     for line in f:
#         l1=line.split('\t')
#         u=int(l1[0])
#         i=int(l1[1])
#         rat=int(l1[2])
#         user.add(u)
#         item.add(i)
#         d1[(u,i)]=rat
# tt=int(len(user)/5)+1

# mat=np.zeros((len(user),len(item)))

# for ele in d1:
#     u=ele[0]-1
#     i=ele[1]-1
#     rat=d1[ele]
#     mat[u,i]=rat

# no_of_cluster=10
# kmeans = KMeans(n_clusters=10, random_state=0).fit(mat)
# d1=dict()
# clusters=[[]]*no_of_cluster
# for i in range(len(kmeans.labels_)):
#   label=kmeans.labels_[i]
#   clusters[label].append(i)
#   d1[i]=label
  
##### d1 gives cluster label of users

##### mat is rating matrix


In [85]:
import random

def find(x,lis):
  lis=list(lis)
  try:
    return lis.index(x)+1
  except:
    return 0

hit=0
arhr=0
TopN=20
for u in users:
  predicted_max= pred_rating[u].argsort()[-TopN:][::-1]
  true_max=mat[u].argsort()[-TopN:][::1]
  rand_num=random.randint(0,TopN-1)
  pos=find(true_max[rand_num],predicted_max)
#   print(pos)
  if(pos!=0):
    hit+=1
    arhr+=1/pos
#     print('hit')
#   else:
#     print('miss')
# print(len(users))
HR=hit/len(users)
ARHR=arhr/len(users)

print("HR:",HR)
print("ARHR:",ARHR)

HR: 0.44
ARHR: 0.08353111245909245


In [0]:
l=np.array([1,2,3,40,5,6,7,8,9,10])
predicted_max= l.argsort()[-5:][::-1]
print(predicted_max)
print(l[predicted_max])


[3 9 8 7 6]
[40 10  9  8  7]
