In [2]:
from google.colab import drive 
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [3]:
!pip install xlrd

    100% |████████████████████████████████| 112kB 2.7MB/s 


In [0]:
from scipy import spatial

import pickle
import numpy as np 
import pandas as pd
from pandas.tools.plotting import scatter_matrix
from random import randint
from sklearn.cluster import KMeans
import numpy as np
from scipy import spatial
from operator import itemgetter
from scipy.cluster.vq import vq, kmeans, whiten
import matplotlib.pyplot as plt
d1=dict()
user=set()
item=set()
# with open('/content/drive/My Drive/IIITD/CF_project/MovieLens Dataset/u.data') as f:
#     for line in f:
#         l1=line.split('\t')
#         u=int(l1[0])
#         i=int(l1[1])
#         rat=int(l1[2])
#         user.add(u)
#         item.add(i)
#         d1[(u,i)]=rat
# tt=int(len(user)/5)+1

# mat=np.zeros((len(user),len(item)))

# for ele in d1:
#     u=ele[0]-1
#     i=ele[1]-1
#     rat=d1[ele]
#     mat[u,i]=rat

# raw_movies_data = pd.read_json("/content/drive/My Drive/IIITD/CF_project/FlickScore Dataset/movies.json", lines=True)
# unique_movie_id = raw_movies_data['movie_id'].unique()

# raw_users_data = pd.read_json("/content/drive/My Drive/IIITD/CF_project/FlickScore Dataset/users.json", lines=True)
# unique_user_id = raw_users_data['_id'].unique()

# raw_ratings_keys = ['_id', 'rated']
# raw_ratings = pd.read_json("/content/drive/My Drive/IIITD/CF_project/FlickScore Dataset/ratings.json",lines=True)
# print(raw_ratings.shape)

# user_item = pd.DataFrame(index=unique_user_id, columns=unique_movie_id)

# for i in range(raw_ratings.shape[0]):
#     a = raw_ratings.iloc[i][0]
#     list_keys = raw_ratings.iloc[i][1]
#     for el in list_keys:
#         if (el != 'submit'):
#             if(int(list_keys[el][0])==-1):
#               user_item[el][a]=0
#             elif(int(list_keys[el][0])==0):
#               user_item[el][a]=5
#             else:
#               user_item[el][a]=10
            

# user_item.fillna(0,inplace=True)
# mat=np.array(user_item)
# mat=np.nan_to_num(mat)
# print(mat.shape)
# print(np.unique(mat))

hg=pd.read_excel(open("/content/drive/My Drive/IIITD/CF_project/Jester Dataset/jester-data-2.xls","rb"),header=None)

In [0]:
mat=np.array(hg.drop([0],axis=1))+10

mat[mat==109]=0

In [15]:
user=(range(mat.shape[0]))
print(user)
item=(range(mat.shape[1]))
print(item)

range(0, 23500)
range(0, 100)


In [16]:
print(mat[0,:])

[ 0.   18.11  0.    0.    7.72  5.78 15.49  7.38  0.    7.72 15.34 13.54
  0.29 13.3   4.42  3.93  9.71 12.33 13.93  9.66  3.11  7.91  1.17  0.
 15.15 13.98 14.47 13.88 15.29  0.   17.09  7.77  0.    0.   13.11  5.58
  0.    4.13  0.    2.72  0.    5.29  1.07  0.   13.4   2.82 12.28 17.48
 15.15 15.73  0.    0.   15.78 13.2   9.56 15.73  0.    0.    0.    0.
  1.75 14.61  0.    0.    6.02 14.9   0.    5.68  7.28  0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.   11.21  0.    0.    0.    0.    0.    0.    4.08
  0.    0.    0.    0.  ]


In [24]:
no_of_cluster=40
kmeans = KMeans(n_clusters=10, random_state=0).fit(mat)
d1=dict()
clusters=[]
for i in range(no_of_cluster):
  l1=[]
  clusters.append(l1)
for i in range(len(kmeans.labels_)):
  label=kmeans.labels_[i]
  clusters[label].append(i)
  d1[i]=label


print(kmeans.labels_)
n=len(user)
m=len(item)

S=np.random.rand(m,m)
cluster=[]
for i in range(10):
  pg=np.random.rand(m,m)
  cluster.append(pg)
  
#learning rate
alpha=0.001
#regularization constants
gu=np.full((n,1),0.5)
g1u=np.full((n,1),0.5)

beta1=0.5
beta2=0.5

iter=100

#global similarity
global1=np.zeros((m,m))
print('here1')
for i in range(m):
  for j in range(m):
    if i==j:
      global1[i][j]=1
    else:
      l1=mat[:,i]
      l2=mat[:,j]
      s=1-spatial.distance.cosine(l1,l2)
      global1[i][j]=s
      
no_of_clusters=40
cl=[]
for ele in clusters:
  mat1=np.zeros((len(user),len(item)))
  for ele1 in ele:
    mat1[ele1,:]=mat[ele1,:]
  local=np.zeros((m,m))
  for i in range(m):
    for j in range(m):
      if i==j:
        local[i][j]=1
      else:
        l1=mat1[:,i]
        l2=mat1[:,j]
        s=1-spatial.distance.cosine(l1,l2)
        local[i][j]=s
  local=local.tolist()
  cl.append(local)
# import json
# with open('/content/drive/My Drive/CF_project/ML/global.json', 'w') as outfile:
#     json.dump(global1.tolist(), outfile)
# print("global")
# with open('/content/drive/My Drive/CF_project/ML/local.json', 'w') as outfile:
#     json.dump(cl, outfile)
# print("local")


  
# Dataset='MovieLens Dataset'
# dfile = open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/cluster_10', 'wb')       
# # source, destination 
# pickle.dump(d1, dfile)                      
# dfile.close() 
# print("cluster_10")

# dfile = open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/rating_Matrix', 'wb')       
# # source, destination 
# pickle.dump(mat, dfile)                      
# dfile.close() 
# print("rating_matrix")

# with open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/global.json', 'w') as outfile:
#     json.dump(mat1.tolist(), outfile)
# print("global")
# with open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/local.json', 'w') as outfile:
#     json.dump(cl, outfile)
# print("local")

[9 5 0 ... 9 1 0]
here1


/usr/local/lib/python3.6/dist-packages/scipy/spatial/distance.py:698: RuntimeWarning: invalid value encountered in double_scalars
  dist = 1.0 - uv / np.sqrt(uu * vv)


In [10]:
print(global1[:5,:5])
print(np.array(cl)[0][:5,:5])


[[1.         0.83603864 0.85257945 0.81761196 0.67159818]
 [0.83603864 1.         0.81037074 0.78272175 0.69608988]
 [0.85257945 0.81037074 1.         0.82240783 0.67609719]
 [0.81761196 0.78272175 0.82240783 1.         0.64420958]
 [0.67159818 0.69608988 0.67609719 0.64420958 1.        ]]
[[1.         0.23734477 0.44099009 0.23081938 0.09713818]
 [0.23734477 1.         0.22794648 0.24747771 0.18040431]
 [0.44099009 0.22794648 1.         0.2645387  0.10316759]
 [0.23081938 0.24747771 0.2645387  1.         0.08990782]
 [0.09713818 0.18040431 0.10316759 0.08990782 1.        ]]


In [25]:
  
Dataset='Jester Dataset'
dfile = open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/cluster_20', 'wb')       
# source, destination 
pickle.dump(d1, dfile)                      
dfile.close() 
print("cluster_20")

dfile = open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/rating_Matrix', 'wb')       
# source, destination 
pickle.dump(mat, dfile)                      
dfile.close() 
print("rating_matrix")


cluster_20
rating_matrix


In [26]:
import json
with open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/global_20.json', 'w') as outfile:
    json.dump(global1.tolist(), outfile)
print("global")
with open('/content/drive/My Drive/IIITD/CF_project/'+Dataset+'/local_20.json', 'w') as outfile:
    json.dump(cl, outfile)
print("local")

global
local
